# --- tmuxp Configuration for Web Development ---

session_name: dynamic_project_name # This line is required by your tmuxp version. It will be overridden by the script.

windows:
  - window_name: editor-terminal # Primary window for coding and general commands
    layout: main-horizontal  # Divides the window horizontally (editor on top, terminal on bottom)
    options:
      main-pane-height: 70%
    panes:
      - shell_command: # Pane 1 (Top): Your Nvim editor
          - nvim . # Opens nvim in the current directory.
      - shell_command: # Pane 2 (Bottom): General purpose terminal
          - clear # Clears the terminal output when the pane starts
          # Add any initial commands you want to run here:
          # - ls -F
          # - git status

  - window_name: browsersync # Dedicated window for BrowserSync server
    panes:
      - shell_command:
          - clear # Clears the terminal output
          - ./start_browsersync.sh # Executes your BrowserSync launch script.


